const courseData = [
  {
    id: 1,
    name: "Learn Figma in 14 Days - Master the Tool Figma",
    rating: 4.5,
    numRatings: 30000,
    price: 3499,
    // image: Icons.crs1,
  },
  {
    id: 2,
    name: "JavaScript Basics: Beginner's Guide to JavaScript",
    rating: 4.3,
    numRatings: 25000,
    price: 2999,
    // image: Icons.crs2,
  },
  {
    id: 3,
    name: "Python for Data Science and Machine Learning Bootcamp",
    rating: 4.7,
    numRatings: 40000,
    price: 4499,
    // image: Icons.crs3,
  },
  {
    id: 4,
    name: "React - The Complete Guide (incl Hooks, React Router, Redux)",
    rating: 4.8,
    numRatings: 50000,
    price: 3999,
    // image: Icons.crs4,
  },
  {
    id: 5,
    name: "Java Programming Masterclass for Software Developers",
    rating: 4.6,
    numRatings: 35000,
    price: 4999,
    // image: Icons.crs5,
  },
  {
    id: 6,
    name: "The Complete Node.js Developer Course (3rd Edition)",
    rating: 4.4,
    numRatings: 28000,
    price: 3799,
    // image: Icons.crs6,
  },
  {
    id: 7,
    name: "Machine Learning A-Z™: Hands-On Python & R In Data Science",
    rating: 4.5,
    numRatings: 32000,
    price: 4599,
    // image: Icons.crs7,
  },
  {
    id: 8,
    name: "Complete C# Unity Game Developer 2D",
    rating: 4.7,
    numRatings: 38000,
    price: 3899,
    // image: Icons.crs8,
  },
  {
    id: 9,
    name: "Angular - The Complete Guide (2022 Edition)",
    rating: 4.6,
    numRatings: 27000,
    price: 3999,
    // image: Icons.crs9,
  },
  {
    id: 10,
    name: "iOS & Swift - The Complete iOS App Development Bootcamp",
    rating: 4.8,
    numRatings: 42000,
    price: 4999,
    // image: Icons.crs10,
  },
  {
    id: 11,
    name: "Complete Blender Creator: Learn 3D Modelling for Beginners",
    rating: 4.4,
    numRatings: 22000,
    price: 3499,
    // image: Icons.crs11,
  },
  {
    id: 12,
    name: "Deep Learning A-Z™: Hands-On Artificial Neural Networks",
    rating: 4.6,
    numRatings: 28000,
    price: 4599,
    // image: Icons.crs12,
  },
  {
    id: 13,
    name: "Complete Java Masterclass: Learn Java From Scratch",
    rating: 4.7,
    numRatings: 35000,
    price: 3999,
    // image: Icons.crs13,
  },
  {
    id: 14,
    name: "Complete React Native Bootcamp: Build iOS and Android Apps",
    rating: 4.5,
    numRatings: 30000,
    price: 4499,
    // image: Icons.crs14,
  },
  {
    id: 15,
    name: "Complete SQL + Databases Bootcamp: Zero to Mastery",
    rating: 4.6,
    numRatings: 32000,
    price: 3999,
    // image: Icons.crs15,
  },
  {
    id: 16,
    name: "The Complete Digital Marketing Course - 12 Courses in 1",
    rating: 4.8,
    numRatings: 42000,
    price: 4999,
    // image: Icons.crs16,
  },
  {
    id: 17,
    name: "The Web Developer Bootcamp 2022: Learn HTML, CSS, JS, Node & More!",
    rating: 4.7,
    numRatings: 38000,
    price: 3899,
    // image: Icons.crs17,
  },
  {
    id: 18,
    name: "Complete Machine Learning & Data Science Bootcamp 2022",
    rating: 4.5,
    numRatings: 32000,
    price: 4599,
    // image: Icons.crs18,
  },
  {
    id: 19,
    name: "Complete Python Developer in 2022: Zero to Mastery",
    rating: 4.6,
    numRatings: 37000,
    price: 3999,
    // image: Icons.crs19,
  },
  {
    id: 20,
    name: "The Complete JavaScript Course 2022: From Zero to Expert!",
    rating: 4.8,
    numRatings: 43000,
    price: 4999,
    // image: Icons.crs20,
  },
];

export default courseData;
